server.servlet.context-path: /petstore

server.port: 9999

spring:
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/vaadin-petstore
    username: petuser
    password: petpass
  jpa:
    generate-ddl: false
    properties:
      #database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        ddl-auto: none
        #ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    jpa:
      show-sql: true

liquibase:
  change-log: db/changelog/db.changelog-master.yaml

vaadin.urlMapping: /ui/*

logging.level:
  liquibase: debug
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.springframework.jdbc.core.JdbcTemplate: debug
  org.springframework.jdbc.core.StatementCreatorUtils: trace

management:
  endpoints:
    configprops.enabled: true
    beans.enabled: true
    shutdown.enabled: true
    enabled-by-default: true
    sensitive: false
    enabled: true
    web.exposure.include: "*"