spring.application.name: vaadin-petstore
server.servlet.context-path: /petstore

spring.jackson.serialization.indent_output: true

# Use PORT env var/sys prop from services like Heroku
server.port: ${PORT:9999}
server.tomcat.additional-tld-skip-patterns: '*.jar'

spring:
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:vaadin-petstore;DB_CLOSE_ON_EXIT=FALSE
    username: petuser
    password: petpass
  jpa:
    database: h2
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
 #       generate_statistics: true
    show-sql: false
    open-in-view: false
  mustache.check-template-location: false

liquibase:
  change-log: db/changelog/db.changelog-master.yaml

vaadin.urlMapping: /ux/*

logging.level:
  org.atmosphere.cpr: warn
  liquibase: info
  org.hibernate.SQL: info
  org.hibernate.type.descriptor.sql.BasicBinder: info
  org.springframework.jdbc.core.StatementCreatorUtils: info
  org.springframework.jdbc.core.JdbcTemplate: info

management:
  security.enabled: false.
  endpoints:
    configprops.enabled: true
    beans.enabled: true
    shutdown.enabled: true
    enabled-by-default: true
    sensitive: false
    enabled: true
    web.exposure.include: "*"
  endpoint.health.health.show-details: always

# logging.path is unusable because ${java.io.tmpdir} in it is empty
logging-path: "${java.io.tmpdir:/tmp/}${spring.application.name}/"
logging:
  file:
    name: "${logging-path}${spring.application.name}.log"
  logback.rollingpolicy:
    file-name-pattern: "${logging.path}${spring.application.name}-%d{yyyy-MM-dd}.%i.log"
    max-file-size: 5MB
    max-history: 50
    total-size-cap: 1000MB

management.metrics.enable.jvm: true
management.metrics.enable.all: true

# log viewer
#logs.base.dir: "${logging.path}"
log-viewer.accessible-files.pattern: "${logging-path}/*.log*,/var/log/*log*,${user.home}/*log,${user.home}/*out"
log-viewer.disable-default-configuration-loader: true
#log-viewer.custom.aggregated.logs.url=/all-logs/*
#log-viewer.custom.aggregated.logs: ${logs.base.dir}/app/logviewer-poc.log,${logs.base.dir}/raw/logviewer-poc.log

web-shell:
  root: /web-shell
  hostshells: zsh,bash,sh
  history:
    file: "./${spring.application.name}.logs/web-shell-history.log"
