server.servlet.context-path: /petstore

# Use PORT env var/sys prop from services like Heroku
server.port: ${PORT:9999}

spring:
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url:  jdbc:h2:mem:vaadin-petstore;DB_CLOSE_ON_EXIT=FALSE
    username: petuser
    password: petpass
  jpa:
    database: h2
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: false
    open-in-view: false
  mustache.check-template-location: false

liquibase:
  change-log: db/changelog/db.changelog-master.yaml

vaadin.urlMapping: /ui/*

logging.level:
  org.atmosphere.cpr: warn
  # debug
  liquibase: info
  org.hibernate.SQL: info
  # trace
  org.hibernate.type.descriptor.sql.BasicBinder: info
  org.springframework.jdbc.core.StatementCreatorUtils: info
  # debug
  org.springframework.jdbc.core.JdbcTemplate: info

management:
  endpoints:
    configprops.enabled: true
    beans.enabled: true
    shutdown.enabled: true
    enabled-by-default: true
    sensitive: false
    enabled: true
    web.exposure.include: "*"
