spring.application.name: vaadin-petstore
server.servlet.context-path: /petstore

spring.boot.admin.context-path: /sba

# Use PORT env var/sys prop from services like Heroku
server.port: ${PORT:9999}
server.tomcat.additional-tld-skip-patterns: '*.jar'

spring:
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url:  jdbc:h2:mem:vaadin-petstore
    username: petuser
    password: petpass
  jpa:
    database: h2
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        generate_statistics: true
    show-sql: false
    open-in-view: false
  mustache.check-template-location: false

liquibase:
  change-log: db/changelog/db.changelog-master.yaml

vaadin.urlMapping: /ux/*

logging.level:
  org.atmosphere.cpr: warn
  liquibase: info
  org.hibernate.SQL: info
  org.hibernate.type.descriptor.sql.BasicBinder: info
  org.springframework.jdbc.core.StatementCreatorUtils: info
  org.springframework.jdbc.core.JdbcTemplate: info

management:
  security.enabled: false.
  endpoints:
    configprops.enabled: true
    beans.enabled: true
    shutdown.enabled: true
    enabled-by-default: true
    sensitive: false
    enabled: true
    web.exposure.include: "*"
  endpoint.health.health.show-details: always

logging.file.name: /var/log/${spring.application.name}.log
#management.endpoint.logfile.external-file: ./logs/logviewer-sba.log
management.metrics.enable.jvm: true
management.metrics.enable.all: true

# log viewer
logs.base.dir: /var/log/
log-viewer.accessible-files.pattern: ${logs.base.dir}/*.log,${logs.base.dir}/raw/*log*
log-viewer.disable-default-configuration-loader: true

#log-viewer.custom.aggregated.logs.url=/all-logs/*
log-viewer.custom.aggregated.logs: ${logs.base.dir}/app/logviewer-poc.log,${logs.base.dir}/raw/logviewer-poc.log

web-shell:
  root: /web-shell
  hostshells: zsh,bash,sh
  history:
    file: ${java.io.tmpdir}/web-shell/history.log

sfe4j:
  title: "SFE4J Demo"
  description: "Simple File Explorer for spring-boot based Java Web Application."
  quick-links:
    root: "/"
    logs: "/var/log"
  base-dir-path: "./"
  restrict-to-base-dir: false
