databaseChangeLog:
- changeSet:
    id: create customer
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_5
            name: ID
            type: BIGINT
        - column:
            name: FIRST_NAME
            type: VARCHAR(255)
        - column:
            name: LAST_NAME
            type: VARCHAR(255)
        tableName: CUSTOMER
- changeSet:
    id: create pet
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_1
            name: ID
            type: BIGINT
        - column:
            name: NAME
            type: VARCHAR(255)
        - column:
            name: SPECIES_ID
            type: BIGINT
        tableName: PET
- changeSet:
    id: create purchase
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_9
            name: ID
            type: BIGINT
        - column:
            name: DATE
            type: TIMESTAMP
        - column:
            name: CUSTOMER_ID
            type: BIGINT
        - column:
            name: PET_ID
            type: BIGINT
        tableName: PURCHASE
- changeSet:
    id: create species
    author: petstore
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: CONSTRAINT_B
            name: ID
            type: BIGINT
        - column:
            name: NAME
            type: VARCHAR(255)
        tableName: SPECIES
- changeSet:
    id: create purchase to customer index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: CUSTOMER_ID
        indexName: FK2PEHE23HWDCYQL94C531RBF70_INDEX_9
        tableName: PURCHASE
- changeSet:
    id: create pet to species index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: SPECIES_ID
        indexName: FK99R3YE65N5D263QXACWFU6EF1_INDEX_1
        tableName: PET
- changeSet:
    id: create purchae to pet index
    author: petstore
    changes:
    - createIndex:
        columns:
        - column:
            name: PET_ID
        indexName: FKG45AM5A8S90EOP5BJG3TT0CEM_INDEX_9
        tableName: PURCHASE
- changeSet:
    id: create purchase to customer fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: CUSTOMER_ID
        baseTableName: PURCHASE
        constraintName: FK2PEHE23HWDCYQL94C531RBF70
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: CUSTOMER
        validate: true
- changeSet:
    id: create pet to species fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: SPECIES_ID
        baseTableName: PET
        constraintName: FK99R3YE65N5D263QXACWFU6EF1
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: SPECIES
        validate: true
- changeSet:
    id: create purchase to pet fk
    author: petstore
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: PET_ID
        baseTableName: PURCHASE
        constraintName: FKG45AM5A8S90EOP5BJG3TT0CEM
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: ID
        referencedTableName: PET
        validate: true

- changeSet:
    id: load data
    author: petstore
    changes:
    - loadData:
        file: species.tsv
        relativeToChangelogFile: true
        separator: '	'
        quotchar: ''''
        tableName: SPECIES
    - loadData:
          file: pet.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: PET
    - loadData:
          file: customer.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: CUSTOMER
    - loadData:
          file: purchase.tsv
          relativeToChangelogFile: true
          separator: '	'
          quotchar: ''''
          tableName: PURCHASE
